# Site settings
title: 
email:
author:
description: "Sobha Rajvilas, new luxurious apartments by Sobha Limited located in Rajaji Nagar, Bangalore. Find details like Sobha Rajvilas Price, Location & Floor Plan"
url: https://sinuprabhu.github.io/sobharajvilas/
baseurl: /sobharajvilas

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Build settings
permalink: :title/
sass:
  sass_dir: /assets/css